- name: conditions in ansible
  hosts: local
  connection: local
  vars:
    IS_LIVE: true
  tasks:
  - name: check live or not
    ansible.builtin.debug:
      msg: "yes, it is live"
    when: IS_LIVE
  - name: check live or not
    ansible.builtin.debug:
      msg: "No, it is not live"
    when: IS_LIVE