- name: demo on filters
  hosts: local
  connection: local
  vars:
    Topics: Ansible, linux, shell
    tagsMap:
    name: ansible
    project: roboshop
    component: catalogue
  tasks:
  - name: convert into list
    ansible.builtin.debug:
      msg: "{{ Topics | split (',') }}"  # convert string to list
      
  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tagsMap | dict2items }}"