- name: demo on filters
  hosts: local
  connection: local
  vars:
    Topics: Ansible, linux, shell
    tagsMap:
      name: ansible
      project: roboshop
      component: catalogue
    tagslist: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
     ]

  tasks:
  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ Topics | split (',') }}"  # convert string to list

  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tagsMap | dict2items }}"

  - name: convert list to map
    ansible.builtin. debug:
      msg: "{{ tagslist | items2dict }}"